// auto generated by go tool dist

package sys

const DefaultGoroot = `/home/james/.linuxbrew/Cellar/go/1.8.1/libexec`
const TheVersion = `go1.8.1`
const Goexperiment = ``
const StackGuardMultiplier = 1

